name: My First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Me
        run: echo "Hello, Ram! How are you?"
      - name: Goodbye Me
        run: echo "Goodbye, Ram! See you later!"
  second-job:
    needs: first-job
    runs-on: windows-latest
    steps:
      - name: Greet and say goodbye!
        run: |
          echo "Hello, Ram! How are you?"
          echo "Goodbye, Ram! See you later!"
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output the github context info
        run: echo "${{ github}}"
